# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 857a9663321476b0ae6669228af672bb451cd8a1b0d9ee51b17bd92ac18258554937ae0d05cb46bb58d3451d301eed03399b45a5ad307981e236fccbbdb27e3d

test:
  secret_key_base: 5bb137a91be115a6ecbbe07fa4b869dd11bd6df594af4df479fe258aaec82ed82a5eb64d4ef79717021df49fd880a5c0beac7053e85cc195a7cf2584c06b56d4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
